baseURL = "https://philipp.steinroetter.com"
languageCode = "en-En"
theme = "PaperMod"
title = "Philipp Steinr√∂tter"

[params]
description = "Full-Stack Developer and Entrepreneur"
dateFormat = "2006-01-02"
readMore = false

social = [
    { id = "github", url = "https://github.com/psteinroe" },
    { id = "email", url = "philipp@steinroetter.com" },
    { id = "x", url = "https://x.com/psteinroe" },
    { id = "bluesky", url = "https://bsky.app/profile/psteinroe.com" }
]

[homeInfoParams]
Title =  "Hi there wave"
Content = "Can be Info, links, about..."

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[params.author]
name = "psteinroe"
email  = "philipp@steinroetter.com"
location = "Berlin"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[pagination]
pagerSize = 5

